
---
name: awscreate
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - dev
          - prod
jobs:
  con-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run aws dev
        env:
         ENVIRONMENT: ${{ inputs.environment }}
        run: |
         if [[ $ENVIRONMENT == 'dev' ]]; then
          - name: Terraform Init
            uses: hashicorp/terraform-github-actions/init@v0.4.0
            env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             TF_ACTION_WORKING_DIR: 'terraform'
             AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
             AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

         - name: Terraform Validate
           uses: hashicorp/terraform-github-actions/validate@v0.3.7

         - name: Terraform Apply
           uses: hashicorp/terraform-github-actions/apply@v0.4.0
           env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           TF_ACTION_WORKING_DIR: 'terraform'
           AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        - name: Sync S3
          uses: jakejarvis/s3-sync-action@master
          env:
          SOURCE_DIR: './src'
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: '[BUCKET_NAME_HERE]'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
         elif [[ $ENVIRONMENT == 'prod' ]]; then
          echo  "prod environment"
         fi
         
