---
name: awscreate
on: push
jobs:
 con-integration:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - name: run aws dev
     run: |
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
        GITHUB_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESSKEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_KEY }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7
      - name: Sync S3
        env:
        SOURCE_DIR: './src'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: 'orangetexinfraterraformbucket'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      
      
         
