name: awscreate
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
        - AWS
        - Azure
        
jobs:
  cont-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Environment
        run: | 
          if("${{ github.event.inputs.environment }}"-eq 'AWS')
            {
            echo "aws environment is chosen" }
          if("${{ github.event.inputs.environment }}"-eq 'AZURE')
            {
                        echo "azure environment is chosen" }
            }
          

