---
name: AWS Infra Creation Using in HCP Terraform
on:
  workflow_call:
    secrets:
      TERRAFORM_TOKEN:
        required: true
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
env:
  tfcode_path: ./src
  tfc_organisation: orangetex
  tfc_workspace: ./terraform
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSKEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
jobs:
  aws_tfc_job:
    name: Create AWS Infra Using TFC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tf code in runner environment
        uses: actions/checkout@v3.5.2
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
      - name: Terraform init and validate
        run: |
          echo `pwd`
          echo "** Running Terraform Init**"
          terraform init
           
          echo "** Running Terraform Validate**"
          terraform validate
          working-directory: ${{ env.tfcode_path }}
      - name: Terraform Plan
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.0
        id: run
        with:
          workspace: ${{ env.tfc_workspace }}
          plan_only: true
          message: Plan Run from GitHub Actions
          token: ${{ secrets.TERRAFORM_TOKEN }}
      - name: Terraform Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.3.0
        id: plan-output
        with:
          token: ${{ secrets.TERRAFORM_TOKEN }}
          plan: ${{ steps.run.outputs.plan_id }}
      - name: Reference Plan Output
        run: |
          echo "Plan status: ${{ steps.plan-output.outputs.plan_status }}"
          echo "Resources to Add: ${{ steps.plan-output.outputs.add }}"
          echo "Resources to Change: ${{ steps.plan-output.outputs.change }}"
          echo "Resources to Destroy: ${{ steps.plan-output.outputs.destroy }}"
  apply_terraform_plan:
    needs: aws_tfc_job
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN}}
      - name: Terraform init and validate
        run: |
          echo `pwd`
          echo "** Running Terraform Init**"
          terraform init

          echo "** Running Terraform Validate**"
          terraform validate
        working-directory: ${{ env.tfcode_path }}
      - name: Terraform Apply
        run: echo "** Running Terraform Apply**"; terraform apply -auto-approve
        working-directory: ${{ env.tfcode_path }}
     # - name: Terraform Destroy
     #   run: echo "** Running Terraform Destroy**"; terraform destroy -auto-approve
     #  working-directory: ${{ env.tfcode_path }}
