---
name: awscreate
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - dev
          - prod
jobs:
  con-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run aws dev
        env:
         ENVIRONMENT: ${{ inputs.environment }}
        run: |
         if [[ $ENVIRONMENT == 'dev' ]]; then
          echo "dev environment"
         elif [[ $ENVIRONMENT == 'prod' ]]; then
          echo  "prod environment"
         fi
         
