---
name: awscreate
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - dev
          - prod
jobs:
  con-integration:
    runs-on: ubuntu-latest
    steps: |
      - uses: actions/checkout@v4
       if: github.event.inputs.environment == 'dev'
       run: echo "dev environment"
       #if: github.event.inputs.environment == 'prod'
       # run: echo  "prod environment"
