---
name: awscreate
on: push
jobs:
 con-integration:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - name: run aws dev
     run: |
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESSKEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_KEY }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      
      
         
