name: awscreate
on: push
jobs:
 cont-integration:
    runs-on: ubuntu-latest #github-runner
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: secrets scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
