---
name: AWS Infra Creation Using in HCP Terraform
on:
  workflow_call:
    secrets:
      TERRAFORM_TOKEN:
        required: true
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  aws_tfc_job:
    name: Create AWS Infra Using TFC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tf code in runner environment
        uses: actions/checkout@v3.5.2
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESSKEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
         aws-region: 'us-east-2'
      - name: terraform initialize
        uses: hashicorp/setup-terraform@v2.0.2
        with:
         terraform_version: 1.4.6
         #cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
      - name: Terraform init and validate
        run: |
          echo "** Running Terraform Init**"
          terraform init
          echo "** Running Terraform Validate**"
          terraform validate
          echo "** Running Terraform Plan**"
          terraform plan -input=false
          echo "** Running Terraform Apply**"
          terraform apply -auto-approve
     # - name: Terraform Destroy
     #   run: echo "** Running Terraform Destroy**"; terraform destroy -auto-approve
     #  working-directory: ${{ env.tfcode_path }}
