name: awscreate
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
        - AWS
        - AZURE
        
jobs:
  cont-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Environment
        run: | 
           if ("${{ github.event.inputs.environment }}" -eq 'AWS') {
            write-host "AWS was selected"
                        } 
           if ("${{ github.event.inputs.environment }}" -eq 'AZURE') {
            write-host "AZURE was selected"
                        } 
            
          

