name: awscreate
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
        - AWS
        - AZURE
        
jobs:
  cont-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Environment
        run: |
          if("${{inputs.environment }}" == 'AWS') 
          write-host "environment is AWS" 
        # run:|
         # if("${{ github.event.inputs.environment}}" == 'AZURE') 
       #   echo "environment is Azure"
